syntax on
filetype plugin indent on
set background=dark
colorscheme wildcharm

nnoremap <SPACE> <Nop>
let mapleader=" "

set mouse=r

set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set expandtab
set cursorline
set hidden
set autoread
set splitbelow splitright
set scrolloff=3
set updatetime=300

set hlsearch incsearch
set ignorecase smartcase

" XDG state and cache directories
let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.cache') : $XDG_CACHE_HOME
let s:state_home = empty($XDG_STATE_HOME) ? expand('~/.local/state') : $XDG_STATE_HOME
let s:backup_dir = s:cache_home . '/vim/backup'
let s:swap_dir = s:cache_home . '/vim/swap'
let s:undo_dir = s:state_home . '/vim/undo'
let s:view_dir = s:state_home . '/vim/view'

for s:dir in [s:backup_dir, s:swap_dir, s:undo_dir, s:view_dir]
  if !isdirectory(s:dir)
    silent! call mkdir(s:dir, 'p', 0700)
  endif
endfor

let &backupdir = s:backup_dir . '//'
let &directory = s:swap_dir . '//'
let &viewdir = s:view_dir
if exists('+viminfofile')
  let &viminfofile = s:state_home . '/vim/viminfo'
endif
if has('persistent_undo') && isdirectory(s:undo_dir)
  let &undodir = s:undo_dir . '//'
  set undofile
endif

unlet s:cache_home s:state_home s:backup_dir s:swap_dir s:undo_dir s:view_dir s:dir

set showcmd

set ruler

set number relativenumber
" nnoremap <silent> <leader>n :set number!<CR>
nnoremap <silent> <leader>n :set number! relativenumber!<CR>

highlight CursorLineNR ctermfg=red

set showbreak=↪\ 
set listchars=tab:»\ ,eol:↲,nbsp:⎵,trail:•,extends:⟩,precedes:⟨
nnoremap <silent> <leader>l :set invlist<CR>

nnoremap <silent> <leader>Q :qa!<CR>
nnoremap <silent> <leader>w :w<CR>
nnoremap <silent> <leader>x :x<CR>

augroup filetype_settings
  autocmd!
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType gitconfig setlocal ts=8 sts=0 sw=8 noet
  autocmd FileType gitcommit setlocal tw=72
augroup END

augroup auto_reload
  autocmd!
  autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * checktime
augroup END

if has('timers')
  if exists('s:auto_reload_timer')
    call timer_stop(s:auto_reload_timer)
  endif
  let s:auto_reload_timer = timer_start(
        \ 1000,
        \ {timer -> execute('checktime')},
        \ {'repeat': -1})
endif

" automatically move the cursor to the last position
augroup restore_cursor
  autocmd!
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | execute "normal! g'\"" | endif
augroup END
